import { theme } from 'antd'

export const customTheme = {
	algorithm: theme.defaultAlgorithm,
	token: {
		colorPrimary: 'var(--primary)',
		colorSuccess: 'var(--success)',
		colorWarning: 'var(--warning)',
		colorError: 'var(--danger)',
		colorInfo: 'var(--info)',
		colorBgLayout: 'var(--bg-dark)',
		colorBgContainer: 'var(--bg-light)',
		colorBgElevated: 'var(--bg-light)',
		colorText: 'var(--text)',
		colorTextSecondary: 'var(--text-muted)',
		colorTextHeading: 'var(--text)',
		colorBorder: 'var(--border)',
		colorBorderSecondary: 'var(--border-muted)',
		colorPrimaryHover: 'var(--info)',
		colorPrimaryActive: 'var(--primary)',
		colorFillSecondary: 'var(--bg)',
		colorFillTertiary: 'var(--bg-dark)',
		colorFillQuaternary: 'var(--bg-light)',

		borderRadius: 6,
	},
	components: {
		Layout: {
			bodyBg: 'var(--bg-dark)',
			headerBg: 'var(--bg-light)',
			triggerBg: 'var(--primary)',
			triggerColor: 'var(--highlight)',
		},
		Card: {
			colorBgContainer: 'var(--bg-light)',
			colorBorderSecondary: 'var(--border-muted)',
		},
		Button: {
			colorPrimary: 'var(--primary)',
			colorPrimaryHover: 'var(--info)',
			colorPrimaryActive: 'var(--primary)',
			defaultBg: 'var(--bg-light)',
			defaultColor: 'var(--text)',
			defaultBorderColor: 'var(--border)',
			defaultHoverColor: 'var(--info)',
			defaultHoverBorderColor: 'var(--info)',
			defaultHoverBg: 'var(--bg-light)',
			primaryShadow: 'none',
			textHoverBg: 'var(--bg)',
			linkHoverBg: 'transparent',
		},
		Input: {
			colorBgContainer: 'var(--bg-light)',
			colorBorder: 'var(--border)',
			colorPrimaryHover: 'var(--primary)',
			colorPrimary: 'var(--primary)',
			hoverBorderColor: 'var(--primary)',
			activeBorderColor: 'var(--primary)',
			addonBg: 'var(--bg)',
		},
		InputNumber: {
			colorBgContainer: 'var(--bg-light)',
			colorBorder: 'var(--border)',
			colorPrimaryHover: 'var(--primary)',
			colorPrimary: 'var(--primary)',
			hoverBorderColor: 'var(--primary)',
			activeBorderColor: 'var(--primary)',
		},
		DatePicker: {
			colorBgContainer: 'var(--bg-light)',
			colorBorder: 'var(--border)',
			colorPrimaryHover: 'var(--primary)',
			colorPrimary: 'var(--primary)',
			hoverBorderColor: 'var(--primary)',
			activeBorderColor: 'var(--primary)',
		},
		Select: {
			colorBgContainer: 'var(--bg-light)',
			colorBorder: 'var(--border)',
			colorPrimary: 'var(--primary)',
			colorPrimaryHover: 'var(--primary)',
			optionSelectedBg: 'var(--bg)',
			optionActiveBg: 'var(--bg-dark)',
		},
		Checkbox: {
			colorPrimary: 'var(--primary)',
			colorBgContainer: 'var(--bg-light)',
		},
		Radio: {
			colorPrimary: 'var(--primary)',
			colorBgContainer: 'var(--bg-light)',
		},
		Menu: {
			colorPrimary: 'var(--primary)',
			itemSelectedBg: 'var(--bg-dark)',
			itemHoverBg: 'var(--bg)',
			itemColor: 'var(--text)',
			itemSelectedColor: 'var(--primary)',
			itemHoverColor: 'var(--primary)',
		},
		Table: {
			colorBgContainer: 'var(--bg-light)',
			borderColor: 'var(--border-muted)',
			headerBg: 'var(--bg-dark)',
			headerColor: 'var(--text)',
			headerSplitColor: 'var(--border-muted)',
			rowHoverBg: 'var(--bg)',
		},
		Modal: {
			colorBgContainer: 'var(--bg-light)',
			colorBgElevated: 'var(--bg-light)',
			headerBg: 'var(--bg-light)',
		},
		Drawer: {
			colorBgContainer: 'var(--bg-light)',
			colorBgElevated: 'var(--bg-light)',
			headerBg: 'var(--bg-light)',
		},
		Tabs: {
			colorBgContainer: 'transparent',
			colorBorderSecondary: 'var(--border-muted)',
			itemColor: 'var(--text-muted)',
			itemSelectedColor: 'var(--primary)',
			itemHoverColor: 'var(--primary)',
			inkBarColor: 'var(--primary)',
		},
		Form: {
			labelColor: 'var(--text)',
			labelRequiredMarkColor: 'var(--danger)',
			itemMarginBottom: 16,
			errorItemBg: 'transparent',
		},
		Alert: {
			colorErrorBg: 'var(--bg-dark)',
			colorErrorBorder: 'var(--danger)',
			colorError: 'var(--danger)',
			colorWarningBg: 'var(--bg-dark)',
			colorWarningBorder: 'var(--warning)',
			colorWarning: 'var(--warning)',
			colorSuccessBg: 'var(--bg-dark)',
			colorSuccessBorder: 'var(--success)',
			colorSuccess: 'var(--success)',
			colorInfoBg: 'var(--bg-dark)',
			colorInfoBorder: 'var(--info)',
			colorInfo: 'var(--info)',
		},
		Tooltip: {
			colorBgSpotlight: 'var(--danger)',
			colorText: 'var(--highlight)',
		},

		List: {
			colorBgContainer: 'var(--bg-light)',
			colorBorder: 'var(--border)',
		},
		Descriptions: {
			colorBgContainer: 'var(--bg-light)',
		},
	},
}
